### ISSUE TITLE
Read file

### ISSUE THREAD

**Issue by aberba** [kaleidicassociates/xlsxd#10]
Hello, nice tool and very handy. Is there plans to add support for reading cells?

**Comment by burner** [comment]
Currently, not. xlsxd is just a wrapper around an existing c library. I haven't searched for any library to read xlsx yet. PR are welcome

**Comment by huangyy** [comment]
xlsx is support to read xlsx file and easy to use.

**Comment by burner** [comment]
I put that in the readme as well
