### ISSUE TITLE
compile error in windows

### ISSUE THREAD

**Issue by huangyy** [kaleidicassociates/xlsxd#12]
git 1.0.2, and compile in windows (vs 15, mingw64), report not found zlib.
so, build zlib 1.2.11 by vs 15, then copy zlib.lib into xlsxd\libxlsxwriter\lib and zlib.h into xlsxd\libxlsxwriter\include. rebuild xlsxd:
dub build --build=release --arch=x86_64 --compiler=ldc2 
also report not found zlib:
CMake Error at cmake/FindPackage.cmake:180 (message):
  Unable to find requested ZLIB libraries.
how to solve this problem ?

**Comment by burner** [comment]
not sure, looks like there are two size_t definitions. Not sure what is going on there.

**Comment by burner** [comment]
try the current version, I think I got it to work, at least on win64. dub test --arch=x86_64 works on my windows 10 vm

**Comment by huangyy** [comment]
great, its work, ths! 
some error and solve:
1.  add C:\Users\huangyy\AppData\Local\dub\packages\xlsxd-1.1.0\xlsxd to PATH, and run windepbuild.bat correct.
2. edit windepbuild.bat, i use vs 15, so edit  "Visual Studio 15 2017 Win64" to "Visual Studio 14 2015 Win64".
3. xlsxd\libxlsxwriter\src\theme.c compile error in line 38, 72, delete it.
4. in my project, link error: 
LINK : warning LNK4098: 默认库“libcmt”与其他库的使用冲突；请使用 /NODEFAULTLIB:library
LINK : warning LNK4098: 默认库“libvcruntime”与其他库的使用冲突；请使用 /NODEFAULTLIB:library 
so, edit dub.json to add:
	"lflags-windows": [
		"/NODEFAULTLIB:libcmt",
		"/NODEFAULTLIB:libvcruntime"		
	],
its ok.

**Comment by burner** [comment]
ok

the windepbuild.bat is easy to fix.
figuring out which Visual Studio version to use to compile might be a bit more difficult. I will check that out.
I'm not sure about the last two

**Comment by burner** [comment]
in v1.2.0 most of your manual steps should be automatically, maybe even all.

**Comment by burner** [comment]
should be working now
