### ISSUE TITLE
building always dirties dub cache

### ISSUE THREAD

**Issue by John-Colvin** [kaleidicassociates/xlsxd#20]
even if nothing happens, dub thinks something has, so everything downstream is rebuilt

**Comment by burner** [comment]
win and/or poxis

**Comment by John-Colvin** [comment]
both IIRC

**Comment by burner** [comment]
I'll have a look

**Comment by burner** [comment]
release v1.2.3 should fix this

**Comment by John-Colvin** [comment]
This seems to still be happening.

I tried changing the preGenerateCommands to preBuildCommands and that helped

**Comment by burner** [comment]
I saw that as well, but I think it is not actually building anything. Just printing something and then the makefile figures out that there is nothing to do.
I'll will investigate and change non the less.

**Comment by burner** [comment]
I still get
```sh
Running pre-build commands...
make: Entering directory '/home/burner/Workspace/xlsxd'
make: 'source/libxlsxd/xlsxwrap.d' is up to date.
make: Leaving directory '/home/burner/Workspace/xlsxd'
make: Entering directory '/home/burner/Workspace/xlsxd'
make: 'libxlsxwriter/build/libxlsxwriter.a' is up to date.
make: Leaving directory '/home/burner/Workspace/xlsxd'
```
