### ISSUE TITLE
Corrupted output with `workbook.addWorksheet(null)`

### ISSUE THREAD

**Issue by tchaloupka** [kaleidicassociates/xlsxd#28]
I've found that when I use this and at least Excel 2016 I've got an error that the file is broken (fix by excel works fine).

It's unexpectedly caused by this: https://github.com/kaleidicassociates/xlsxd/blob/master/source/libxlsxd/workbook.d#L58

And it's because `std.string.toStringz` returns empty string when called with null. So there is empty named sheet in the output which caused the error.
See https://github.com/dlang/phobos/blob/master/std/string.d#L311

I'm not sure what to do with this. I would expect that `toStringz` would return `null` for `null` input. So this is probably Phobos bug or should we "fix" it in this library?

**Comment by burner** [comment]
I think that null.toStringz() == "" makes sense for toStingz. I will fix it in the library and pass null if name.empty. 

Thank you for caring

**Comment by burner** [comment]
new release with fix https://github.com/kaleidicassociates/xlsxd/releases/tag/v2.0.4

**Comment by tchaloupka** [comment]
Thanks!
